Select ccp.DS_CONCEPTO,
  vcp.DS_ALIAS_VIA_COBRO_PAGO,
  tp.DS_TIPO_PREVISION,
  td.DS_TIPO_DOCUMENTO,
  tf.DS_FLUJO_CAJA,
  p.*
from KAT_PREVISIONES p
  inner join KAT_CONCEPTOS_COBRO_PAGO ccp on p.CD_CONCEPTO = ccp.CD_CONCEPTO
  inner join KAT_VIAS_COBRO_PAGO vcp on p.CD_VIA_COBRO_PAGO = vcp.CD_VIA_COBRO_PAGO
  inner join KAT_TIPO_PREVISION tp on p.CD_TIPO_PREVISION = tp.CD_TIPO_PREVISION
  inner join KAT_TIPO_DOCUMENTO td on p.CD_TIPO_DOCUMENTO = td.CD_TIPO_DOCUMENTO
  inner join KAT_TIPO_FLUJO_CAJA tf on ccp.CD_FLUJO_CAJA = tf.CD_FLUJO_CAJA